server:
  port: 8080
spring:
  application:
    name: jwt-token-security
    datasource:
      url: jdbc:h2:mem:security
      username: test
      password: test
      driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
security:
  jwt:
    key-store: classpath:my_key_store.jks
    key-store-password: qwerty123456
    key-pair-alias: my_key_store
    key-pair-password: qwerty123456
    clientId: GWMZP9RQOP1Y40
    secret: fO8WqqVW
    scopes:
      - read
      - write
    authorizedGrantTypes:
      - password
      - refresh_token
      - client_credentials
    authorities:
      - ROLE_CLIENT
    grant_type: password
    accessTokenValiditySeconds: 1000
    refreshTokenValiditySeconds: 10000
    auth_host: ${AUTH_HOST}
logging:
  level:
    ROOT: WARN
    org.springframework.security: TRACE
    com.popov.*: DEBUG
